# 管理窗口行为和工作区（虚拟桌面）的设置
############################################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
############################################

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# layerrule = blur, waybar

layerrule = blur, logout_dialog

layerrule = blur, notifications
layerrule = blurpopups, notifications # mako的弹窗
layerrule = xray 1, notifications

# windowrule = opacity 1.0 override, class:Rofi # 禁用rofi的不透明度
layerrule = blur, rofi
layerrule = xray 1, rofi
layerrule = ignorealpha 0, rofi # 解决rofi边角的透明度问题等，忽略透明度，以不透明像素方式渲染
layerrule = blurpopups, rofi


# windowrule = fullscreenstate 2 1,class:chromium # 强制应用全屏

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

